name: carnd-term3
channels:
    - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
dependencies:
    - python==3.5.2
    - numpy==1.12.1
    - matplotlib==2.0.1
    - jupyter==1.0.0
    - opencv
    - tqdm
    - scikit-learn==0.18.1
    - scikit-image==0.13.0
    - scipy==0.19.0
    - h5py==2.7.0
    - seaborn==0.7.1
    - pandas==0.20.1
    - tensorflow-gpu==1.2.1
    - pip:
        - keras==2.0.4
        - pydot==1.2.3
        - graphviz==0.7.1
